// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;git
import org.openqa.selenium.Keys;
import java.util.*;
public class MySelenium {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void testUpload() {
    driver.get("http://172.16.250.220/index_blue.jsp");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.name("userid")).click();
    driver.findElement(By.name("userid")).sendKeys("maxy");
    driver.findElement(By.name("pwd")).click();
    driver.findElement(By.name("pwd")).sendKeys("123456");
    driver.findElement(By.name("Submit1")).click();
    driver.switchTo().frame(0);
    driver.findElement(By.id("ext-gen59")).click();
    driver.switchTo().frame(2);
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.id("create")).click();
    vars.put("win1094", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win1094").toString());
    driver.findElement(By.id("htfj")).click();
    driver.findElement(By.id("htfj")).sendKeys("C:\\fakepath\\[人人都是产品经理]苏杰.pdf");
    driver.findElement(By.linkText("确认")).click();
    driver.findElement(By.linkText("作废")).click();
    driver.findElement(By.linkText("确认")).click();
    driver.findElement(By.linkText("确认")).click();
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
  }
}
